spring.application.name=vivek-bhalke
# DB
spring.datasource.url=jdbc:sqlite:local_db.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect


# Custom path to access the raw JSON structure of your APIs
springdoc.api-docs.path=/api-docs

# Custom path to access the interactive web dashboard interface
springdoc.swagger-ui.path=/swagger-ui.html
